import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from './components/Navbar'
import './globals.css'
import 'react-responsive-carousel/lib/styles/carousel.min.css'

import { FavouritesProvider } from '@/context/favourites.context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cat lover app',
  description: 'Generated by Tomasz',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={inter.className + ' min-h-screen bg-sky-50 text-slate-500'}
      >
        <Navbar />

        <main>
          <div className="max-w-screen-xl mx-auto py-6">
            <FavouritesProvider>{children}</FavouritesProvider>
          </div>
        </main>
        {modal}
      </body>
    </html>
  )
}
